accessing
headerArrayForCSVExport
	^ #(
	'Project'
	'Number of test classes'
	'Minimum class depth'
	'Median class depth'
	'Maximum class depth'
	'Number of tests'
	'Number of helpers'
	'Minimum max helper depth'
	'Median max helper depth'
	'Maximum max helper depth'
	'Minimum primitive calls in test count'
	'Median primitive calls in test count'
	'Maximum primitive calls in test count'
	'Minimum helper calls in test count'
	'Median helper calls in test count'
	'Maximum helper calls in test count'
	'Insidious cat. 1'
	'Insidious cat. 2'
	'Insidious cat. 3'
	'Insidious cat. 4'
	)