Class {
	#name : #RTFRow16HelperNotExecutedAssertionNotExecutedContainsNoHelperContainsNoAssertion,
	#superclass : #RTFAbstractTestCaseForPaper,
	#category : 'RottenTestsFinder-FakePaperTests'
}

{ #category : #tests }
RTFRow16HelperNotExecutedAssertionNotExecutedContainsNoHelperContainsNoAssertion >> test [
	"Does nothing."
]

{ #category : #tests }
RTFRow16HelperNotExecutedAssertionNotExecutedContainsNoHelperContainsNoAssertion >> test2 [
	self methodDoingNothing
]
