Class {
	#name : #RTFRow01HelperExecutedAssertionExecutedContainsHelperContainsAssertion,
	#superclass : #RTFAbstractTestCaseForPaper,
	#category : 'RottenTestsFinder-FakePaperTests'
}

{ #category : #tests }
RTFRow01HelperExecutedAssertionExecutedContainsHelperContainsAssertion >> test [
	self assert: true
]

{ #category : #tests }
RTFRow01HelperExecutedAssertionExecutedContainsHelperContainsAssertion >> test2 [
	self goodHelper
]

{ #category : #tests }
RTFRow01HelperExecutedAssertionExecutedContainsHelperContainsAssertion >> test3 [
	self goodHelperWrapper
]
